---
title: "FFBS for Coupled HMM"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Notation: 


$Z_t^{[c]}$ denote the hidden state variable of chain $c \in \{1, \ldots, C\}$ at time $t\in \{1, \ldots, T\}$ with a finite set of possible states, $G$ -- assuming the same number of states for each chain

$Z_t^{[c]} \in \Omega = \{1, \ldots, G\}$

Nonhomogeneous Markov chain in which the transition probabilities depend on time given by: 

$Pr(Z_t^{[c]} = j | Z_{t-1}^{[c]} = i, \boldsymbol{Z}_{t-1}^{[c]}, \boldsymbol{\theta})$

$\forall i,j \in \Omega$, for $Z_{t-1}^{[-c]}$ denotes $\left(Z_{t-1}^{[1]}, Z_{t-1}^{[2]}, \ldots, Z_{t-1}^{[C]} \right)$ with $Z_{t-1}^{c}$ removed 

$Y_t^{[c]}$ denotes the observation variables, which we assume to be generated according to the underlying state process $Z_t^{[c]}$


Let $f(Y_t^{[c]} = y_t^{[c]}|Z_t^{[c]} = g, \boldsymbol{\theta}) = f_g(y_t^{[c]}|\boldsymbol{\theta}) \quad g \in G$ denote the probability density/mass function for $y_t^{[c]}$. If missing, we set $f_g(y_t^{[c]}|\boldsymbol{\theta}) = 1$. 

where $\boldsymbol{\theta}$ represents any and all other parameters requiring estimation

__Assumptions:__ 

- Every chain has the same number of observations $T$ -- (in the future, what would happen with time series of varying length? In what cases would this make sense?)
- Every chain has the same number of states (for now -- Sherlock extended this)
- Assumption that the observation is missing `at random'


 
## Likelihood and Posterior


__Complete-data likelihood__




Let $\pi(\boldsymbol{\theta})$ denote the joint prior distribution of all parameters. 



